version: '3'
services:
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - client
      - urlhandler
  mongodb:
    build:
      context: ./services/mongodb
      dockerfile: Dockerfile
    container_name: mongoDB
    ports:
      - "27017:27017"
  urlhandler:
    build:
      context: services/urlhandler
      dockerfile: Dockerfile
    container_name: urlhandler
    expose:
      - 5000
  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    container_name: client
    expose:
      - 5000
